### ISSUE TITLE
td_ngramsplitter returns a list, not tbl_teradata

### ISSUE THREAD

**Issue by mattsq** [Teradata/tdplyr#2]
`td_ngramsplitter` returns a two-part list object with attributes instead of a `tbl_teradata` object, which means that it can't be used in a tidy piped workflow without an unnecessary call to `{.$result}`. If attributes are useful in some downstream way, there are other ways to use S3 classes to give objects properties without needing to mess up the object.

e.g.:

```r
data("storms")
copy_to(td_con, 
        storms,
        name = "storms",
        temporary = TRUE, 
        overwrite = TRUE, 
        analyze = TRUE)
## doesn't work
con %>%
  tbl(in_schema(schema = username, table = "storms")) %>%
  td_ngramsplitter(text.column = "status", grams = c("1")) %>%
  select(name, year, ngram)
## has to be:
con %>%
  tbl(in_schema(schema = username, table = "storms")) %>%
  td_ngramsplitter(text.column = "status", grams = c("1")) %>%
  {.$result} %>%
  select(name, year, ngram)
```

**Comment by jerisalan** [comment]
Hey @mattsq, 

It is how we envisioned tdplyr to work and what you pointed out is really not an issue. If you don't know, tdplyr works on the principle of lazy evaluation and lazy queries to avoid too much computation and also to avoid the need to bring data to the frontend as much as possible. 

When you end up calling the `td_ngramsplitter` function, the execution really hasn't taken place and only when you try to print the object or access its result attribute does the execution happen. 

```
> storms_ng <- td_ngramsplitter_sqle(data = storms_tbl, text.column = "status", grams = c("1"))
> storms_ng
############ result ############

# Source:   SQL [?? x 1]
# Database: Teradata
# Groups:  
   name   year month   day  hour   lat  long status category  wind pressure ts_diameter
   <chr> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <chr>  <chr>    <int>    <int>       <dbl>
 1 Cesar  1984     8    31    18  39.8 -63.1 tropi… 0           35      999          NA
 2 Cesar  1984     9     1     0  40.6 -61.1 tropi… 0           40      999          NA
 3 Cesar  1984     9     1     0  40.6 -61.1 tropi… 0           40      999          NA
 4 Cesar  1984     9     1     6  41.7 -59   tropi… 0           40      998          NA
 5 Mich…  2000    10    17     0  29.9 -71.1 tropi… 0           35     1003          NA
 6 Mich…  2000    10    17     6  29.8 -71   tropi… 0           45     1000          NA
 7 Mich…  2000    10    17     6  29.8 -71   tropi… 0           45     1000          NA
 8 Mich…  2000    10    17    12  29.8 -70.9 tropi… 0           55      995          NA
 9 Mich…  2000    10    17    12  29.8 -70.9 tropi… 0           55      995          NA
10 Mich…  2000    10    17    18  30.1 -70.9 hurri… 1           65      988          NA
# … with more rows, and 4 more variables: hu_diameter <dbl>, ngram <chr>, n <int>,
#   frequency <int>

> class(storms_ng)
[1] "td_ngramsplitter_sqle" "td_analytics_sql"      "td_analytics"         
[4] "list"                 
> class(storms_ng$result)
[1] "tbl_teradata" "tbl_dbi"      "tbl_sql"      "tbl_lazy"     "tbl" 
``` 
As you can see above, the `storms_ng` object just acts as an wrapper to hold the underlying lazy tibble which is in `result`. Adopting this methodology also becomes very useful when certain SQLE or MLE analytic function can return multiple tables as their output and the list object can be container to hold each corresponding table output as an lazy tibble.

**Comment by mattsq** [comment]
Hey! I definitely get the lazy concept - I'm not sure returning just a result would interrupt that - `x <- tbl %>% select(...)` is lazy until `x` is evaluated as well in the usual dbplyr case. 

Totally get case where a function returns more than one table, but here I don't see why you couldn't assign the other part of the list object to `attr` - and only make multipart objects when the object really is multipart in terms of the data output.

Close away if this is intended behaviour, though.

**Comment by jerisalan** [comment]
I do totally understand and get your point but we stuck to adopting the design as it could bring more consistentency across all our analytic function APIs. Hence, I will close the issue.
