### ISSUE TITLE
Functions return 'table does not exist' when user doesn't have CREATE TABLE permission

### ISSUE THREAD

**Issue by mattsq** [Teradata/tdplyr#3]
Recently while testing out Vantage we noticed a wide range of the VALLIB functions weren't working, often returning a 'table does not exist' error. It was hard to debug these until cross-checking their application in Teradata and realising that the issue is that `tdplyr` tries to create a table when executing, rather than just returning the result (not an awesome outcome, because the database is quickly filled with random temporary tables with names like `r__t__valib_td_association_valib1631600092624000_11`) but when it is unable to do so, it doesn't fail with a insufficient permissions error, it just silently fails to make the table and then errors out on trying to find the table it didn't make. 

An error indicating the permissions error would be vastly preferable!

**Comment by jerisalan** [comment]
@mattsq,
Thanks for reporting this. Can you please paste a full log of the error stack trace for the expression that contributed to this error? We need to check if this is something that the tdplyr engineering team or the teradata driver team needs to address.

**Comment by mattsq** [comment]
Here's an example:
```
> td_con %>%
+   tbl(sql("SEL* FROM storms_copy")) %>%
+   tdplyr::td_adaptive_histogram_valib(columns = "lat")
Error in `db_query_fields.DBIConnection()`:
! Can't query fields.
Caused by error in `obtainRows()`:
! [Version 17.20.0.25] [Session 24898410] [Teradata Database] [Error 3807] Object 'FUEL_ENV.r__t__valib_td_adaptive_histogram_valib168631058417491' does not exist.
 at gosqldriver/teradatasql.formatError ErrorUtil.go:89
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError ErrorUtil.go:217
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError ErrorUtil.go:233
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:827
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:2298
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:865
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:715
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:1331
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1757
 at database/sql.withLock sql.go:3439
 at database/sql.(*DB).queryDC sql.go:1752
 at database/sql.(*Conn).QueryContext sql.go:2011
 at main.createRows goside.go:783
 at main.rgoCreateRows goside.go:639
 at _cgoexp_2a23d297bb44_rgoCreateRows _cgo_gotypes.go:359
 at runtime.cgocallbackg1 cgocall.go:316
 at runtime.cgocallbackg cgocall.go:235
 at runtime.cgocallback asm_amd64.s:994
 at runtime.goexit asm_amd64.s:1594
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by lcl-teradata** [comment]
Hey @mattsq we acknowledge this issue and we will prioritize it in upcoming releases.

**Comment by lcl-teradata** [comment]
Hey @mattsq, With the recent release of tdplyr 17.0.0.4, appropriate error is thrown when the database is out of memory or if it has insufficient permissions.
Screenshot of appropriate error being displayed in attached:
![val_install](https://github.com/Teradata/tdplyr/assets/131337508/403ff07f-079d-473c-aaa4-dedf209d6175)
